return {
 
    designButtonText = "Design a plane",
    techtreeButtonText = "Research",
    networkButtonText = "Check the map",
    purchaseButtonText = "Buy airplanes",
    mapButtonText = "View the map",
    fleetButtonText = "View fleets",
    cashText = "Cash on hand: ",
    debtText = "Outstanding debt: ",
    investmentText = "Seek investment",
    loanText = "Take out a loan",
    planesdevText = "Planes in development",
    char_type = "Engine Type",
    char_category = "Category",
    char_size = "Size",
    char_config = "Configuration",
    char_fueltype = "Fuel Type",
    char_fuelamount = "Fuel Amount",
    char_engineconfig = "Engine Configuration",
    category_small = "Small",
    category_medium = "Medium",
    category_large = "Large",
    category_mega = "Mega",
    specs_title = "Specifications",
    specs_weight = "Weight = ",
    specs_speed = "Avg Speed = ",
    specs_topspeed = "Top Speed = ",
    specs_range = "Range = ",
    specs_capacity = "Capacity = ",
    specs_efficiency = "Efficiency = ",
    specs_emissions = "Emissions = ",
    specs_fuel = "Fuel = ",
    flow_dev = "Send to Development",
    flow_compare = "Compare",
    flow_save = "Save Design",
    flow_load = "Load Design",
    flow_reset = "Reset",
    flow_return = "Return to main",
    demand_title = "DEMAND\nCurrent Fleet / Likely Purchases",
    demand_consumer = "Passenger aircraft\nFactors:\nEfficiency, Cost, Speed",
    demand_cargo = "Cargo Aircraft\nFactors:\nEfficiency, Cost, Speed",
    demand_premium = "Premium Consumer Aircraft\nFactors:\nSpeed, Cost",
    demand_ultraShort = "Ultra-Short Haul\nSmall aircraft only\nAny range",
    demand_short = "Short Haul Regional\nSmall or Medium aircraft\n1500km+ range", 
    demand_medium = "Meium Haul Domestic\nMedium or Large aircraft\n3000km+ range",
    demand_long = "Long-Haul Intercontinental\nLarge or Mega aircraft\n6000km+ range", 
    demand_ultraLong = "Ultra-Long-Haul Intercontinental\nMega aircraft\n10000km+ range", 
	demand_salesEst = "Total estimated sales demand:",
    demand_units = "units",
	demand_profitEst = "Total estimated profit:",
    dev_prodCostTitle = "Unit production cost",
    dev_salePriceTitle = "Price markup: ",
    dev_unitPrice = "Unit price: ",
    dev_devButton = "Begin development",
    dev_returnButton = "Return to design",
    dev_devCost = "Development cost",
    dev_devTime = "Development time",
    dev_prodCostUnits = " million",
    dev_devCostUnits = " billion",
    dev_prodTimeUnits = " years",
    purch_selectPlane = "Select Plane",
    purch_purchase = "Purchase",
}

