function init(self)
	-- Initialize the airport
end

function on_message(self, message_id, message, sender)
	-- Handle the custom set_light message
	if message_id == hash("set_light") then
		-- Set the light property on the model component
		go.set("#AirportModel", "light", message.light)
	elseif message_id == hash("set_model_position") then
		-- Set the model's position property
		go.set("#AirportModel", "position", message.pos)
	end
end